---
# tasks file for CentOS
- name: Update yum cache
  yum:
    update_cache: yes
- name: Install additional packages
  yum:
    name:
      - epel-release
      - libselinux-python
    state: present
    update_cache: yes
- name: Remove unwanted packages
  yum:
    name:
      - telnet-server
      - talk-server
      - yp-tools
      - ypbind
      - ypserv
    state: absent
    autoremove: yes
    update_cache: yes
