---
# tasks file for CentOS
- name: Update yum cache
  yum:
    update_cache: yes
- name: Enable EPEL repo
  yum:
    name: epel-release
    state: present
    update_cache: yes
- name: Install additional packages
  yum:
    name: "{{ install_pkgs }}"
    state: present
    update_cache: yes
- name: Remove unwanted packages
  yum:
    name: "{{ remove_pkgs }}"
    state: absent
    autoremove: yes
    update_cache: yes
