---
# tasks file for apache
- name: Install Apache for CentOS
  when:
    - ansible_distribution == "CentOS"
  yum:
    name: httpd
    state: present
    update_cache: yes
  notify:
    - Enable httpd
- name: Install Apache for Ubuntu
  when:
    - ansible_distribution == "Ubuntu"
  apt:
    name: apache2
    state: present
    update_cache: yes
  notify:
    - Enable apache2
- name: Install relevant PHP packages
  package:
    name:
      - php
    state: present
    update_cache: yes
- name: Copy templated index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: 0644
- name: Copy info.php
  copy:
    src: info.php
    dest: /var/www/html/info.php
    mode: 0644
