---
# Setup for my centos mgt vm
- name: Setup mgt vm
  hosts: "{{ hostgrp | default('all') }}"
  become: yes
  tasks:
    - name: Install EPEL
      yum:
        name: epel-release
        state: present
        update_cache: yes
    - name: Install ansible and git
      yum:
        name:
          - ansible
          - git
        state: present
        update_cache: yes
    - name: Setup local hosts into /etc/hosts
      blockinfile:
        path: /etc/hosts
        insertafter: EOF
        block: |
          192.168.56.100    centos7-mgt mgt
          192.168.56.105    centos7 centos7-web1
          192.168.56.106    ubuntu18 ubuntu-web1
          192.168.56.110    centos7-awx awx
          192.168.56.115    centos7-2 centos7-web2
    - name: Checkout lca2022-ansible.git
      git:
        repo: "https://github.com/serheang/lca2022-ansible"
        dest: /srv/lca2022-ansible
