---
# tasks file for lamp
- name: Install LAMP for CentOS
  when:
    - ansible_distribution == "CentOS"
  block:
    - name: Setup mysql 8.0 community repo
      package:
        name: "https://dev.mysql.com/get/mysql80-community-release-el{{ ansible_distribution_major_version }}-4.noarch.rpm"
        state: present
        update_cache: yes
    - name: Install httpd
      package:
        name: httpd
        state: present
        update_cache: yes
      notify:
        - Enable httpd
    - name: Install mysql-server
      package:
        name: mysql-server
        state: present
        update_cache: yes
      notify:
        - Enable mysql in CentOS
    - name: Install relevant PHP packages
      package:
        name:
          - php
          - php-mysql
        state: present
        update_cache: yes

- name: Install LAMP for Ubuntu
  when:
    - ansible_distribution == "Ubuntu"
  block:
    - name: Install apache2
      package:
        name: apache2
        state: present
        update_cache: yes
      notify:
        - Enable apache2
    - name: Install mysql-server
      package:
        name: mysql-server
        state: present
        update_cache: yes
      notify:
        - Enable mysql in Ubuntu
    - name: Install relevant PHP packages
      package:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
        update_cache: yes

- name: Copy templated index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: 0644

- name: Copy info.php
  copy:
    src: info.php
    dest: /var/www/html/info.php
    mode: 0644
