---
# handlers file for lamp
- name: Enable httpd
  service:
    name: httpd
    enabled: yes
    state: started

- name: Enable mysql in CentOS
  service:
    name: mysqld
    enabled: yes

- name: Enable apache2
  systemd:
    name: apache2
    enabled: yes
    state: started

- name: Enable mysql in Ubuntu
  service:
    name: mysql
    enabled: yes

