---
- hosts: "{{ hostgrp | default('all') }}"
  gather_facts: true
  become: yes
  tasks:
    - name: Setup for CentOS
      when:
        - ansible_distribution == "CentOS"
      block:
        - name: Enable EPEL
          yum: "name=epel-release state=latest"
        - name: Setup MySQL repo - CentOS 6
          when:
            - ansible_distribution_major_version == "6"
          yum:
            name: https://dev.mysql.com/get/mysql80-community-release-el6-4.noarch.rpm
            state: present
            update_cache: yes
        - name: Setup MySQL repo - CentOS 7
          when:
            - ansible_distribution_major_version == "7"
          yum:
            name: https://dev.mysql.com/get/mysql80-community-release-el7-4.noarch.rpm
            state: present
            update_cache: yes
        - name: Install additional packages
          yum:
            name:
              - libselinux-python
            state: installed

    - name: Setup for Ubuntu
      when:
        - ansible_distribution == "Ubuntu"
      block:
        - name: Update apt cache
          apt: 
            update_cache: yes
            cache_valid_time: 5

    - name: Install ansible
      package:
        name: ansible
        state: present
    - name: Install python3
      package:
        name: python3
        state: present
      ignore_errors: yes
    - name: Install MySQL server and PHP
      package:
        name: 
          - mysql-server
          - php
          - php-mysql
        state: present
    - name: Install LAMP - CentOS
      when:
        - ansible_distribution == "CentOS"
      block:
        - name: Install httpd
          yum:
            name:
              - httpd
            state: present
            update_cache: yes
        - name: Enable and start httpd
          service:
            name: httpd
            enabled: yes
            state: started
        - name: Enable and start mysql-server
          service:
            name: mysqld
            enabled: yes
            state: started
        
    - name: Install LAMP - Ubuntu
      when:
        - ansible_distribution == "Ubuntu"
      block:
        - name: Install apache2
          apt:
            name:
              - apache2
              - libapache2-mod-php
            state: present
            update_cache: yes
        - name: Enable and start apache2
          service:
            name: apache2
            enabled: yes
            state: started
        - name: Enable and start mysql-server
          service:
            name: mysql
            enabled: yes
            state: started

    - name: Create customize index.html
      blockinfile:
        path: /var/www/html/index.html
        marker: <!-- {mark} index.html -->
        create: yes
        block: |
          <html>
          <title>Test page for LCA2022</title>
          <body>
          <h1>LCA2022 - Test landing page</h1>
          <h2>{{ ansible_hostname }}</h2>
          <p>Welcome to LCA2022!<p>
          This is running on {{ ansible_hostname }}, OS: {{ ansible_distribution }}, Version: {{ ansible_distribution_major_version }}
          </body>
          </html>
 
    - name: Create customize info.php
      blockinfile:
        path: /var/www/html/info.php
        marker: <!-- {mark} info.php -->
        create: yes
        block: |
          <?php phpinfo(); ?>
      
  handlers:
