---
- hosts: webservers
  become: yes
  tasks:
    - name: Install Apache - CentOS
      when:
        - ansible_distribution == "CentOS"
      block:
        - name: Enable EPEL
          package:
            name: epel-release
            state: present
            update_cache: yes
        - name: Install httpd
          package:
            name:
              - httpd
            state: present
        - name: Enable and start httpd
          service:
            name: httpd
            enabled: yes
            state: started
    - name: Install Apache - Ubuntu
      when:
        - ansible_distribution == "Ubuntu"
      block:
        - name: Install apache2
          package:
            name:
              - apache2
              - libapache2-mod-php
            state: present
        - name: Enable and start apache2
          service:
            name: apache2
            enabled: yes
            state: started
    - name: Install PHP
      package:
        name: 
          - php
        state: present
    - name: Copy templated index.html
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        mode: 0644
    - name: Copy info.php
      copy:
        src: files/info.php
        dest: /var/www/html/info.php
        mode: 0644
