---
- name: Setup for distros
  hosts: all
  become: yes
  tasks:
    - name: Setup for CentOS
      when:
        - ansible_distribution == "CentOS"
      include_role:
        name: CentOS
    - name: Setup for Ubuntu
      when:
        - ansible_distribution == "Ubuntu"
      include_role:
        name: Ubuntu

- name: Apache setup
  hosts: webservers
  tasks:
    - name: Setup Apache
      include_role:
        name: apache
