---
- name: Setup for distros
  hosts: all
  become: yes
  tasks:
    - name: Setup for CentOS
      when:
        - ansible_distribution == "CentOS"
      include_role:
        name: CentOS
    - name: Setup for Ubuntu
      when:
        - ansible_distribution == "Ubuntu"
      include_role:
        name: Ubuntu

- name: Setup for management node
  hosts: management
  become: yes
  tasks:
    - name: Install extra packages
      package:
        name:
          - ansible
          - python3
        state: latest
        update_cache: yes
      ignore_errors: yes

- name: LAMP setup
  hosts: lamp
  tasks:
    - name: Setup LAMP
      include_role:
        name: lamp
