---
- hosts: "{{ hostgrp | default('all') }}"
  become: yes
  tasks:
    - name: Setup for CentOS
      when:
        - ansible_distribution == "CentOS"
      block:
        - name: CentOS
          include_role:
            name: CentOS
    - name: Setup for Ubuntu
      when:
        - ansible_distribution == "Ubuntu"
      block:
        - name: Ubuntu
          include_role:
            name: Ubuntu
    - name: Setup LAMP
      include_role:
        name: lamp
