name: Run this on push
on:
  # Do something on push
  push:
    # Ediot the branches here
    branches:
      - main
      - master

  # Do nothing on pull
  pull_request: []

jobs:
  changes:
    name: Get Git Changed YAML Files
    runs-on: ubuntu-latest
    outputs:
      changed_file: ${{ steps.files.outputs.added_modified }}
    steps:
      - name: files
        uses: tj-actions/changed-files@v13.1
        with:
          files: |
            *.yaml
            *.yml

  verify_ansible:
    needs:
      - changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        changed_file:
          - "${{ fromJson(needs.changes.outputs.changed_file) }}"
        ansible_version:
          - "2.9.25"
    name: Check ${{ matrix.changed_file }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pip
        run: sudo apt -y install python-pip
      - name: Pip install ansible
        run: sudo pip install -y ansible==${{ matrix.ansible_version }}
